live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.7
startup_mode = 'SimpleFullscreen'
decorations_theme_variant = "Dark"

[font]
size = 12
normal = { family = "DroidSansM Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
	{ key = "D", mods = "Control", action = "ReceiveChar" },
]
#  { key = "PageUp",   mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
#  { key = "PageDown", mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
#  { key = "Home",     mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
#  { key = "End",      mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
#  { key = "K",        mods = "Command",       mode = "~Vi|~Search", action = "ReceiveChar" },
#  { key = "F",        mods = "Control|Shift", mode = "~Search",     action = "ReceiveChar" },
#  { key = "F",        mods = "Command",       mode = "~Search",     action = "ReceiveChar" },
#  { key = "B",        mods = "Control|Shift", mode = "~Search",     action = "ReceiveChar" },
#  { key = "B",        mods = "Command",       mode = "~Search",     action = "ReceiveChar" },
#  { key = "Paste",                                            action = "ReceiveChar" },
#  { key = "Copy",                                             action = "ReceiveChar" },
#  { key = "V",        mods = "Control|Shift", mode = "~Vi",         action = "ReceiveChar" },
#  { key = "V",        mods = "Command",                          action = "ReceiveChar" },
#  { key = "C",        mods = "Control|Shift",                    action = "ReceiveChar" },
#  { key = "C",        mods = "Command",                          action = "ReceiveChar" },
#  { key = "C",        mods = "Control|Shift", mode = "Vi|~Search",  action = "ReceiveChar" },
#  { key = "C",        mods = "Command",       mode = "Vi|~Search",  action = "ReceiveChar" },
#  { key = "D",        mods = "Control",			 mode = "Vi|Search|Alt|AppKeypad|AppCursor", action = "ReceiveChar" }
# ]

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

#[colors.cursor]
#cursor = '#c8d3f5'
#text = '#222436'

# Normal colors
[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
[colors.bright]
black = '#444a73'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#c8d3f5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'
