

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.7
startup_mode = 'SimpleFullscreen'
decorations_theme_variant = "Dark"
option_as_alt = "OnlyLeft" 

[font]
size = 12
normal = { family = "DroidSansM Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
	{ key = "D", mods = "Control", action = "ReceiveChar" },
]
#  { key = "PageUp",   mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
#  { key = "PageDown", mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
#  { key = "Home",     mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
#  { key = "End",      mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
#  { key = "K",        mods = "Command",       mode = "~Vi|~Search", action = "ReceiveChar" },
#  { key = "F",        mods = "Control|Shift", mode = "~Search",     action = "ReceiveChar" },
#  { key = "F",        mods = "Command",       mode = "~Search",     action = "ReceiveChar" },
#  { key = "B",        mods = "Control|Shift", mode = "~Search",     action = "ReceiveChar" },
#  { key = "B",        mods = "Command",       mode = "~Search",     action = "ReceiveChar" },
#  { key = "Paste",                                            action = "ReceiveChar" },
#  { key = "Copy",                                             action = "ReceiveChar" },
#  { key = "V",        mods = "Control|Shift", mode = "~Vi",         action = "ReceiveChar" },
#  { key = "V",        mods = "Command",                          action = "ReceiveChar" },
#  { key = "C",        mods = "Control|Shift",                    action = "ReceiveChar" },
#  { key = "C",        mods = "Command",                          action = "ReceiveChar" },
#  { key = "C",        mods = "Control|Shift", mode = "Vi|~Search",  action = "ReceiveChar" },
#  { key = "C",        mods = "Command",       mode = "Vi|~Search",  action = "ReceiveChar" },
#  { key = "D",        mods = "Control",			 mode = "Vi|Search|Alt|AppKeypad|AppCursor", action = "ReceiveChar" }
# ]

## TokyoNight Alacritty Colors
## Default colors
#[colors.primary]
#background = '#222436'
#foreground = '#c8d3f5'

##[colors.cursor]
##cursor = '#c8d3f5'
##text = '#222436'

## Normal colors
#[colors.normal]
#black = '#1b1d2b'
#red = '#ff757f'
#green = '#c3e88d'
#yellow = '#ffc777'
#blue = '#82aaff'
#magenta = '#c099ff'
#cyan = '#86e1fc'
#white = '#828bb8'

## Bright colors
#[colors.bright]
#black = '#444a73'
#red = '#ff757f'
#green = '#c3e88d'
#yellow = '#ffc777'
#blue = '#82aaff'
#magenta = '#c099ff'
#cyan = '#86e1fc'
#white = '#c8d3f5'

## Indexed Colors
#[[colors.indexed_colors]]
#index = 16
#color = '#ff966c'

#[[colors.indexed_colors]]
#index = 17
#color = '#c53b53'


## Sonokai
## Default colors
#[colors.primary]
#background = "0x2c2e34"
#foreground = "0xe2e2e3"

##[colors.cursor]
#cursor = '#c8d3f5'
#text = '#222436'

## Normal colors
#[colors.normal]
#black = "0x181819"
#red = "0xfc5d7c"
#green = "0x9ed072"
#yellow = "0xe7c664"
#blue = "0x76cce0"
#magenta = "0xb39df3"
#cyan = "0xf39660"
#white = "0xe2e2e3"

## Bright colors
#[colors.bright]
#black = "0x7f8490"
#red = "0xfc5d7c"
#green = "0x9ed072"
#yellow = "0xe7c664"
#blue = "0x76cce0"
#magenta = "0xb39df3"
#cyan = "0xf39660"
#white = "0xe2e2e3"

## Indexed Colors
#[[colors.indexed_colors]]
#index = 16
#color = '#ff966c'

#[[colors.indexed_colors]]
#index = 17
#color = '#c53b53'

# # argonaut theme
# # Default colors
# [colors.primary]
# background = '#292C3E'
# foreground = '#EBEBEB'

# # Cursor colors
# [colors.cursor]
# text = '#EBEBEB'
# cursor = '#FF261E'

# # Normal colors
# [colors.normal]
# black   = '#0d0d0d'
# red     = '#FF301B'
# green   = '#A0E521'
# yellow  = '#FFC620'
# blue    = '#1BA6FA'
# magenta = '#8763B8'
# cyan    = '#21DEEF'
# white   = '#EBEBEB'

# # Bright colors
# [colors.bright]
# black   = '#6D7070'
# red     = '#FF4352'
# green   = '#B8E466'
# yellow  = '#FFD750'
# blue    = '#1BA6FA'
# magenta = '#A578EA'
# cyan    = '#73FBF1'
# white   = '#FEFEF8'

# moonfly theme
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#949494"
blue = "#74b2ff"
cyan = "#85dc85"
green = "#36c692"
magenta = "#ae81ff"
red = "#ff5189"
white = "#e4e4e4"
yellow = "#c2c292"

[colors.cursor]
cursor = "#ffffff"
text = "#080808"

[colors.normal]
black = "#323437"
blue = "#80a0ff"
cyan = "#79dac8"
green = "#8cc85f"
magenta = "#cf87e8"
red = "#ff5454"
white = "#c6c6c6"
yellow = "#e3c78a"

[colors.primary]
background = "#080808"
bright_foreground = "#eeeeee"
foreground = "#bdbdbd"

[colors.selection]
background = "#b2ceee"
text = "#080808"
