live_config_reload = true

[window]
decorations = "None"
opacity = 0.7
startup_mode = 'SimpleFullscreen'
decorations_theme_variant = "Dark"

[font]
size = 12
normal = { family = "DroidSansM Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
