[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.7
# startup_mode = 'SimpleFullscreen'
decorations_theme_variant = "Dark"
option_as_alt = "OnlyLeft"

[font]
# size = 12
# normal = { family = "DroidSansM Nerd Font Mono", style = "Regular" }
# size = 12
# normal = { family = "Monaspace Argon Var", style = "Regular" }
# size = 13
# normal = { family = "GohuFont uni14 Nerd Font Mono", style = "Regular" }
size = 15
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [{ key = "D", mods = "Control", action = "ReceiveChar" }]
#  { key = "PageUp",   mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
#  { key = "PageDown", mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
#  { key = "Home",     mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
#  { key = "End",      mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
#  { key = "K",        mods = "Command",       mode = "~Vi|~Search", action = "ReceiveChar" },
#  { key = "F",        mods = "Control|Shift", mode = "~Search",     action = "ReceiveChar" },
#  { key = "F",        mods = "Command",       mode = "~Search",     action = "ReceiveChar" },
#  { key = "B",        mods = "Control|Shift", mode = "~Search",     action = "ReceiveChar" },
#  { key = "B",        mods = "Command",       mode = "~Search",     action = "ReceiveChar" },
#  { key = "Paste",                                            action = "ReceiveChar" },
#  { key = "Copy",                                             action = "ReceiveChar" },
#  { key = "V",        mods = "Control|Shift", mode = "~Vi",         action = "ReceiveChar" },
#  { key = "V",        mods = "Command",                          action = "ReceiveChar" },
#  { key = "C",        mods = "Control|Shift",                    action = "ReceiveChar" },
#  { key = "C",        mods = "Command",                          action = "ReceiveChar" },
#  { key = "C",        mods = "Control|Shift", mode = "Vi|~Search",  action = "ReceiveChar" },
#  { key = "C",        mods = "Command",       mode = "Vi|~Search",  action = "ReceiveChar" },
#  { key = "D",        mods = "Control",			 mode = "Vi|Search|Alt|AppKeypad|AppCursor", action = "ReceiveChar" }
# ]

## TokyoNight Alacritty Colors
## Default colors
#[colors.primary]
#background = '#222436'
#foreground = '#c8d3f5'

##[colors.cursor]
##cursor = '#c8d3f5'
##text = '#222436'

## Normal colors
#[colors.normal]
#black = '#1b1d2b'
#red = '#ff757f'
#green = '#c3e88d'
#yellow = '#ffc777'
#blue = '#82aaff'
#magenta = '#c099ff'
#cyan = '#86e1fc'
#white = '#828bb8'

## Bright colors
#[colors.bright]
#black = '#444a73'
#red = '#ff757f'
#green = '#c3e88d'
#yellow = '#ffc777'
#blue = '#82aaff'
#magenta = '#c099ff'
#cyan = '#86e1fc'
#white = '#c8d3f5'

## Indexed Colors
#[[colors.indexed_colors]]
#index = 16
#color = '#ff966c'

#[[colors.indexed_colors]]
#index = 17
#color = '#c53b53'


## Sonokai
## Default colors
#[colors.primary]
#background = "0x2c2e34"
#foreground = "0xe2e2e3"

##[colors.cursor]
#cursor = '#c8d3f5'
#text = '#222436'

## Normal colors
#[colors.normal]
#black = "0x181819"
#red = "0xfc5d7c"
#green = "0x9ed072"
#yellow = "0xe7c664"
#blue = "0x76cce0"
#magenta = "0xb39df3"
#cyan = "0xf39660"
#white = "0xe2e2e3"

## Bright colors
#[colors.bright]
#black = "0x7f8490"
#red = "0xfc5d7c"
#green = "0x9ed072"
#yellow = "0xe7c664"
#blue = "0x76cce0"
#magenta = "0xb39df3"
#cyan = "0xf39660"
#white = "0xe2e2e3"

## Indexed Colors
#[[colors.indexed_colors]]
#index = 16
#color = '#ff966c'

#[[colors.indexed_colors]]
#index = 17
#color = '#c53b53'

# # argonaut theme
# # Default colors
# [colors.primary]
# background = '#292C3E'
# foreground = '#EBEBEB'

# # Cursor colors
# [colors.cursor]
# text = '#EBEBEB'
# cursor = '#FF261E'

# # Normal colors
# [colors.normal]
# black   = '#0d0d0d'
# red     = '#FF301B'
# green   = '#A0E521'
# yellow  = '#FFC620'
# blue    = '#1BA6FA'
# magenta = '#8763B8'
# cyan    = '#21DEEF'
# white   = '#EBEBEB'

# # Bright colors
# [colors.bright]
# black   = '#6D7070'
# red     = '#FF4352'
# green   = '#B8E466'
# yellow  = '#FFD750'
# blue    = '#1BA6FA'
# magenta = '#A578EA'
# cyan    = '#73FBF1'
# white   = '#FEFEF8'

# moonfly theme
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#949494"
blue = "#74b2ff"
cyan = "#85dc85"
green = "#36c692"
magenta = "#ae81ff"
red = "#ff5189"
white = "#e4e4e4"
yellow = "#c2c292"

[colors.cursor]
cursor = "#F72798"
text = "#080808"

[colors.normal]
black = "#323437"
blue = "#80a0ff"
cyan = "#79dac8"
green = "#8cc85f"
magenta = "#cf87e8"
red = "#ff5454"
white = "#c6c6c6"
yellow = "#e3c78a"

[colors.primary]
background = "#080808"
bright_foreground = "#eeeeee"
foreground = "#bdbdbd"

[colors.selection]
background = "#ffffff"
text = "#080808"

# Nightfox Alacritty Colors
## name: carbonfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/carbonfox/alacritty.toml

# [colors.primary]
# background = "#161616"
# foreground = "#f2f4f8"
# dim_foreground = "#b6b8bb"
# bright_foreground = "#f9fbff"

# [colors.cursor]
# text = "#f2f4f8"
# cursor = "#b6b8bb"

# [colors.vi_mode_cursor]
# text = "#f2f4f8"
# cursor = "#33b1ff"

# [colors.search.matches]
# foreground = "#f2f4f8"
# background = "#525253"

# [colors.search.focused_match]
# foreground = "#f2f4f8"
# background = "#3ddbd9"

# [colors.footer_bar]
# foreground = "#f2f4f8"
# background = "#353535"

# [colors.hints.start]
# foreground = "#f2f4f8"
# background = "#3ddbd9"

# [colors.hints.end]
# foreground = "#f2f4f8"
# background = "#353535"

# [colors.selection]
# text = "#f2f4f8"
# background = "#2a2a2a"

# [colors.normal]
# black = "#282828"
# red = "#ee5396"
# green = "#25be6a"
# yellow = "#08bdba"
# blue = "#78a9ff"
# magenta = "#be95ff"
# cyan = "#33b1ff"
# white = "#dfdfe0"

# [colors.bright]
# black = "#484848"
# red = "#f16da6"
# green = "#46c880"
# yellow = "#2dc7c4"
# blue = "#8cb6ff"
# magenta = "#c8a5ff"
# cyan = "#52bdff"
# white = "#e4e4e5"

# [colors.dim]
# black = "#222222"
# red = "#ca4780"
# green = "#1fa25a"
# yellow = "#07a19e"
# blue = "#6690d9"
# magenta = "#a27fd9"
# cyan = "#2b96d9"
# white = "#bebebe"

# [[colors.indexed_colors]]
# index = 16
# color = "#3ddbd9"

# [[colors.indexed_colors]]
# index = 17
# color = "#ff7eb6"
